### ISSUE TITLE
sql: sqlparser dependency version problem

### ISSUE THREAD

**Issue by hanzheng** [gitql/gitql#90]
hi,

which youtube/vitess sqlparser version should I use to build gitql?

build from source:
gitql tag v0.3.0 with youtube/vitess branch release-2.1

> sql/parse/parse.go:140: tn.Name.String undefined (type sqlparser.TableIdent has no field or method String)
> sql/parse/parse.go:328: undefined: sqlparser.HexVal
> sql/parse/parse.go:343: v.Name.Lowered undefined (type string has no field or method Lowered)

using ```go get```:

> ZhengdeMacBook-Pro:gitql hanzheng$ go get github.com/gitql/gitql
> \#  github.com/gitql/gitql/sql/parse
> sql/parse/parse.go:320: sqlparser.StrVal (type sqlparser.ValType) is not a type
> sql/parse/parse.go:321: cannot convert v (type sqlparser.ValExpr) to type string
> sql/parse/parse.go:324: undefined: sqlparser.NumVal
> sql/parse/parse.go:326: cannot convert v (type sqlparser.ValExpr) to type string
> sql/parse/parse.go:328: sqlparser.HexVal (type sqlparser.ValType) is not a type

thanks.

**Comment by smola** [comment]
@hanzheng Thanks for the report!

As a temporary solution, you can checkout an older version (e.g. `c97b5be7d0116ae15241df7f6a6fe1dbc038b5df`).

Soon we'll update the code and we might vendor the library to avoid future breakage.
